server:
  port: 5250
  servlet:
    context-path: /template

# 应用名称
spring:
  application:
    name: springboot-template
  datasource:
    url: jdbc:mysql://101.43.189.54:52/common?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
    password: wz201405001148
    driverClassName: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: root
      password: 123456


  redis:
    host: 101.43.189.54
    port: 6379
    database: 2
    password: wz201405001148
    lettuce:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 8
        min-idle: 8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  field-strategy: 0